{
 "title": "Threat Intelligence Dashboard",
 "description": "Dashboard for analyzing threats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Счетчик пойманных хакеров",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(security_proxy_requests_total{port=~\"9001|9002\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего обработано запросов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(security_proxy_requests_total{port=~\"9000|9001|9002\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость атаки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(security_proxy_requests_total{port=~\"9001|9002\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение количества запросов по сервисам",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (port) (round(increase(security_proxy_requests_total{port=~\"9001|9002\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение защитных действий",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (action) (round(increase(security_proxy_requests_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Наиболее атакованные порты",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (port) (round(increase(security_proxy_requests_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}